Enabled ability to configure service timezone displaying
RebelCode/rcmod-wp-bookings-ui pull request #55
Opened 2018-07-04 10:49 UTC by romalytvynenko

Helps to fix https://github.com/RebelCode/booking-wizard/issues/3 by enabling display options config input.

2018-07-04 10:49 UTC, romalytvynenko commented
Should be merged AFTER https://github.com/RebelCode/rcmod-wp-bookings-ui/pull/50

2018-07-05 11:23 UTC, XedinUnknown requested changes

2018-07-05 11:23 UTC, XedinUnknown commented on templates/availability/tab-display-options.phtml
> +            Show dates and times on the site using the customer's timezone
I18n.

2018-07-06 14:29 UTC, XedinUnknown approved these changes

2018-07-07 11:08 UTC, merged